# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b589c656ad1f882c92875e7dfa60a5a00691a34a40e114acd8c5eb6ad94ccc43bcac1529a49da1ff762051a4e725647fb893cedbc15f17bb3d914625d5eae04

test:
  secret_key_base: db7dc69d6068bf08ede41c9317622be81f0d3a488ca07bb929682389e9ef71d721cbfb3e89d638cf70ebc341009fef43cdd61fe7910312c4bdaedfa9f734da3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
